baseurl = "https://davidjosearaujo.github.io"
title = "David Araújo"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
enableEmoji=true

[markup.highlight]
style = "github-dark"

[params]
  author = "David Araújo"
  info = "Cybersecurity Student, Graduate Researcher, and full time tech enthusiast!"
  keywords = "portfolio,developer,personal"
  avatarurl = "images/51376165.jpg"

  colorScheme = "auto"
  hidecolorschemetoggle = false

  dateFormat = "January 2, 2006"
  since = 2023

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/davidjosearaujo"
[[params.social]]
  name = "Gmail"
  icon = "fa fa-envelope fa-2x"
  weight = 3
  url = "mailto:david2araujo5@gmail.com"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/david2araujo5/"
[[params.social]]
  name = "Curriculum"
  icon = "fa fa-file fa-2x"
  weight = 4
  url = "https://docs.google.com/document/d/e/2PACX-1vToY47Ukd08Y_0VYEJ3a_-MuDc2biS0gJFshLtZVIDTvbydlej14tlFzfBm3ExdpvlMjn4ZAr4BovJG/pub"

# Menu links

[[menu.main]]
  name = "About Me"
  weight = 1
  url = "about/"
[[menu.main]]
  name = "Projects"
  weight = 2
  url  = "projects/"
[[menu.main]]
  name = "Certifications"
  weight = 3
  url  = "certs/"
[[menu.main]]
  name = "Contact me"
  weight = 4
  url = "contact/"
