baseurl = "https://davidjosearaujo.github.io"
title = "David Araújo"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
enableEmoji=true

[markup.highlight]
style = "github-dark"

[markup.goldmark.renderer]
unsafe = true

[params]
  author = "David Araújo"
  info = "Cybersecurity student and researcher"
  keywords = "portfolio,developer,personal"

  colorScheme = "auto"
  hidecolorschemetoggle = false

  dateFormat = "January 2, 2006"
  since = 2023

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/davidjosearaujo"
[[params.social]]
  name = "Email"
  icon = "fa fa-envelope fa-2x"
  weight = 3
  url = "mailto:david2araujo5@proton.me"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/david2araujo5/"

# Menu links

[[menu.main]]
  name = "About Me"
  weight = 1
  url = "about/"
[[menu.main]]
  name = "Blog"
  weight = 2
  url = "posts/"
